love: &love b4637aff
rose: &rose d7827eff
gold: &gold ea9d34ff
muted: &muted 9893a5ff
monofur: &monofur monofur for Powerline:pixelsize=20
bg_default: &bg_default {stack: [{background: {color: 81A1C1ff}}, {underline: {size: 4, color: D8DEE9ff}}]}

bar:
  height: 32
  location: top
  font: *monofur
  layer: top
  foreground: 575279ff
  background: f2e9e1ff

  right:
    - battery:
        name: BAT0
        content:
          - string: {text: , font: "Font Awesome 6 Free:style=solid:size=12"}
          - string: {text: "{capacity}% "}
    - cpu:
        content:
          map:
            conditions:
              id < 0:
                - string: {text: , font: "Font Awesome 6 Free:style=solid:size=12"}
                - string: {text: "{cpu}% "}
    - mem:
        content:
          - string: {text: , font: "Font Awesome 6 Free:style=solid:size=12"}
          - string: {text: "{percent_used}% "}
    - pulse:
        content:
          map:
            margin: 18
            default: {empty: {}}
            conditions:
              sink_online: 
              - string: {text: , font: "Font Awesome 6 Free:style=solid:size=12"}
              - string: {text: "{sink_percent}%  "}
    - clock:
        content:
          - string: {text: , font: "Font Awesome 6 Free:style=solid:size=12"}
          - string: {text: "{date}", right-margin: 5}
          - string: {text: , font: "Font Awesome 6 Free:style=solid:size=12"}
          - string: {text: "{time}  "}
  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 10
              right-margin: 13
              default: {string: {text: }}
              conditions:
                id == 1: {string: {text: 1}}
                id == 2: {string: {text: 2}}
                id == 3: {string: {text: 3}}
                id == 4: {string: {text: 4}}
                id == 5: {string: {text: 5}}

        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: D08770ff}}
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: {empty: {}}
              state == invisible && occupied:
                map:
                  <<: *river_base
                  deco: {underline: {size: 3, color: ea6962ff}}


  center:
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "   {app-id}", foreground: ffa0a0ff}
                - string: {text: ": {title}"}
